### ISSUE TITLE
Web service for UI?

### ISSUE THREAD

**Issue by boons605** [boons605/MotoGymkhanaRaceTiming#15]
We talked about a web interface for the UI. Creating this issue to collect ideas and links to interesting resources. 

- .NET Core web service on Linux (Pi) https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0
- Web API in .NET Core
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio

**Comment by CptMalfunction** [comment]
Currently im thinking we split this up in 2 projects. The actual api in asp.net core, and the web ui in a blazor project

**Comment by CptMalfunction** [comment]
So now that i've gotten a single endpoint up and running what endpoints do we want? I've got a few here:

- Race monitoring endpoints:
-- GET /RaceState: returns a json that contains riders on track, riders waiting for start. And any device events waitign for a match
-- GET /Laps: returns a json with a list of all the driven laps (including DNF) since the unit was turned on
-- GET /BestLaps: Returns a json with the best lap per driver, sorted by lap time

- Management endpoints:
-- POST /AddRiders: takes a json with a list of all riders that should be tracked by the system
-- DELETE /Rider: takes a rider id as a query param and stops tracking this rider for the current race
-- POST /Config: takes a json that specifies a full race config (id units and timing unit details). Clears the current race state and (re) starts the race with the new settings
-- GET /Lock: takes 'open' or 'closed' as a query parameter. If closed no new riders can start

**Comment by boons605** [comment]
I would like to opt for the option to integrate DSQ and Penalty points and to register those as events with a timestamp (and to be able to undo those and therefore to list them in order of time). Penalty point events could have an amount (configurable?) category?

Could be really helpful in identifying what exactly went wrong: For the rider to improve themselves and when handling disputes after the race. 

Romke Boonstra

**Comment by boons605** [comment]
Maybe add some management operations for listing riders, modifying riders. 

Modifying race results maybe?

**Comment by CptMalfunction** [comment]
I think ill make the management endpoints into a differnt issue. For now im just doing the andpoints for the state and the laps
